---
version: "2"
checks:
  complexity:
    enabled: false
  file-lines:
    enabled: false
  similar-code:
    enabled: false
  indent:
    enabled: false

plugins:
  eslint:
    enabled: true
    config:
      config: .eslintrc.js
    checks:
      indent:
        enabled: false

  fixme:
    enabled: true

exclude_patterns:
  - "node_modules/"
  - "server/migrations"
  - "server/models"
  - "server/seeders"
  - "server/config"
