---
version: "2"
checks:
  file-lines:
    enabled: false
  similar-code:
    enabled: false

engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc.js
    checks:
      complexity:
        enabled: false
  fixme:
    enabled: true

exclude_patterns:
  - "node_modules/"
  - "server/migrations"
  - "server/models"
  - "server/seeders"
  - "server/config"
